### ISSUE TITLE
Throws syntax error

### ISSUE THREAD

**Issue by Auditormadness9** [xen-cyber/Discord-Undetected-Auto-Bump#1]

**Comment by xen-cyber** [comment]
Fill the .env file with the correct information. It's up for me and running perfectly. If you could attach a picture of the error or paste the error as it is i could try and identify the error.

**Comment by Auditormadness9** [comment]
> Fill the .env file with the correct information. It's up for me and running perfectly. If you could attach a picture of the error or paste the error as it is i could try and identify the error.

I did fill it in, here's the error.
![image](https://user-images.githubusercontent.com/71278545/199250363-53c34f35-4166-4302-8baa-f588c122e0e7.png)

I tried running it on Replit too and it didn't return an error but it didn't do anything either.

**Comment by Auditormadness9** [comment]
Update: seems like on Replit it shows this but idk what I am supposed to do:
![image](https://user-images.githubusercontent.com/71278545/199250960-be682750-1a6c-45dd-a52c-4bb85dacb47b.png)

**Comment by Auditormadness9** [comment]
![image](https://user-images.githubusercontent.com/71278545/199314692-b50936a9-0efd-4629-8311-368acd6a5f8a.png)

**Comment by Auditormadness9** [comment]
The Heroku deployment also seems down

**Comment by xen-cyber** [comment]
I run it on a different rep not on this one. Um it seems to work it just need to wait 2 to 2:30 hour to send the first bump tho. But it worked either way. You can manually bump from any user in the bump channel the first time and it should detect it and reset the timer between 2 and 2:30 hours again. If it's unclear send me your discord tag and we can talk.

**Comment by Auditormadness9** [comment]
Well the first error only occurs when I run it on Windows, using whatever it natively uses to run js files.

Regarding bumping, I haven't tried that since it didn't return any text in console and nor did I even see the account whose token I inserted come online, so I thought it didn't work.

**Comment by xen-cyber** [comment]
status is set to invisible you can change that on the ready event

**Comment by xen-cyber** [comment]
![image](https://user-images.githubusercontent.com/77687289/199471346-2a20b817-b0c7-45d9-bab0-71155daea4fc.png)

**Comment by Auditormadness9** [comment]
Okay did that, but bumping still doesn't work, can you add me please?

Auditormadness9#2501

**Comment by Auditormadness9** [comment]
also

![image](https://user-images.githubusercontent.com/71278545/199530005-a4b36402-ab0e-4a53-a188-60691dc5d902.png)

**Comment by Auditormadness9** [comment]
Fixed it bro, replace `'851790745815220234'` with `process.env['CHANNELID']`

**Comment by Auditormadness9** [comment]
@xen-cyber Hey, I am having issues running this on Replit or Codesandbox (any cloud tbh), can you add me on Discord? I was able to run this locally via cmd and it works well, tried it with npm forever as well and is good but it still kinda dies when I shut down PC or put it to sleep so need it to run 24/7 but can't.

**Comment by xen-cyber** [comment]
oh i'm not sure i know for a fact it is deployable on heroku but i'm sorry i can't help you with that issue concerning replit. I will close this issue since it works for you. If you have any other issues please open another one

**Comment by Auditormadness9** [comment]
> oh i'm not sure i know for a fact it is deployable on heroku but i'm sorry i can't help you with that issue concerning replit. I will close this issue since it works for you. If you have any other issues please open another one

Hey sorey for replying after close, but wanted to ask, does Heroku run the script 24/7? I've been on a long tryhard for finding a platform that can help me deploy it and run it 24/7 but whatever I use other than Replit it just stops when I shut down PC, while Replit is buggy and doesn't run it half the time.

**Comment by xen-cyber** [comment]
yes it does but unfortunately heroku will be removing their free VPS in this month november

**Comment by Auditormadness9** [comment]
Yep I finally managed to deploy and use it on Heroku to 24/7 extent as intended, thanks a ton!

Yeah tough luck on me, finally wanted to do this and ended up with this news. Any good replacement you'd suggest?
