### ISSUE TITLE
Selfbot v14

### ISSUE THREAD

**Issue by Auditormadness9** [xen-cyber/Discord-Undetected-Auto-Bump#3]
Any chance [discord.js-selfbot-v14](https://github.com/aiko-chan-ai/discord.js-selfbot-v13/tree/v14) can start to be used by this repo or is there no benefit yet in terms of undetectability or overall ease of operation and stability?

**Comment by xen-cyber** [comment]
it works fine with the earlier version so ig no i won't use v14 at least for now
